# Simple Kubernetes Pod to deploy the app contained in badmmusanu/kubes (docker hub)
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: web
spec:
  containers:
    - name: web-ctr
      image: badmusanu/kubes
      ports:
        - containerPort: 8080
